### PR TITLE
Various coding standards fixes.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Description of the Change

This fixes several small coding standards issues:

* The `%s` placeholders in `$wpdb->prepare()` were quoted but this isn't necessary. WordPress Core handles it but it's recommended against, removing the quotes allows for a couple of `phpcs:ignore` statements to be removed.
* URL encodes the querystring parameter sent to google's ping service. 
* Removes docblock formatting from a couple of multi-line comments. 

Closes #

### Changelog Entry

> Fixed - Various coding standards issues.

### Credits

Props @peterwilsoncc

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by akshitsethi — APPROVED** [review]
💯

**Comment by peterwilsoncc** [comment]
@akshitsethi Are you happy if I merge this and #25 or do you wish to hold off until preparing the next release?

**Comment by jeffpaul** [comment]
@peterwilsoncc still seeing Linting action fail here

**Comment by peterwilsoncc** [comment]
> @peterwilsoncc still seeing Linting action fail here

That's related to the deprecation in the action, I'll create a follow up PR

**Pull request merged**
